services:

  iam:
    image: docker.io/keycloak/keycloak
    network_mode: bridge
    ports:
      - 8080:8080
      - 8443:8443
      - 9000:9000
    environment:
      KC_HOSTNAME: "${KC_HOSTNAME}"
      KC_HOSTNAME_PORT: 8080
      KC_HOSTNAME_STRICT_BACKCHANNEL: "${KC_HOSTNAME_STRICT_BACKCHANNEL}"
      KEYCLOAK_ADMIN: "${KEYCLOAK_ADMIN}"
      KEYCLOAK_ADMIN_PASSWORD: "${KEYCLOAK_ADMIN_PASSWORD}"
      KC_HEALTH_ENABLED: "${KC_HEALTH_ENABLED}"
      KC_LOG_LEVEL: "${KC_LOG_LEVEL}"
    command: ["start-dev", "--http-port", "8080", "--https-port", "8443"]

  # PostgreSQL
  db:
    image: postgres:15.14-bookworm
    restart: always
    # set shared memory limit when using docker compose
    shm_size: 128mb
    network_mode: bridge
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "db_prod" ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s